name: Build
on:
  push:
    branches:
      - '**'
  pull_request: {}

jobs:
  install-criticalup-build-run-my-app:
    name: Install CriticalUp, Install Ferrocene, Build and Run my app
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Make sure CriticalUp is installed and available
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/ferrocene/criticalup/releases/latest/download/criticalup-installer.sh | sh

      - name: Test if CriticalUp is installed
        run: |
          criticalup --help

      - name: Authenticate CriticalUp
        run: |
          criticalup auth set ${{ secrets.CRITICALUP_USER_TOKEN }}

      - name: Install Ferrocene toolchain from the project manifest (criticalup.toml)
        run: |
          criticalup install
      
      - name: Run my app via Ferrocene compiler which was just installed, using CriticalUp
        run: |
          criticalup run cargo run
